#!/usr/bin/env ruby

def help
  puts "Usage: #{$0} [-v]"
  puts " -v  Turn on/off the verbose flag (default: off)"
  exit(-1)
end

verbose = ARGV.delete("-v")

require File.expand_path('./kernel_override', File.dirname(__FILE__)) unless verbose.nil?

system("GREP_OPTIONS= ; gem list | cut -d' ' -f1 | egrep -v '(rake|bundler|passenger|fastthread|daemon_controller)' | xargs gem uninstall -aIx")
system("gem install rake bundler")
system("bundle") if File.exists?("./Gemfile")
