#!/bin/bash

# This script can be used to clone all remote branches of a git repo
# @see http://stevelorek.com/how-to-shrink-a-git-repository.html

# Note: Assumes that the remote's name is 'origin' and the default branch's name is 'master'

for branch in $(git branch -a | grep 'remotes/origin' | egrep -v '(HEAD|master)'); do
  git branch --track ${branch##*/} $branch
done
