#!/usr/bin/env ruby

def help
  puts "Usage: #{$0} [-v] <tag>"
  puts " -v   Turn on/off the verbose flag (default: off)"
  puts " tag  Required parameter specifying which tag to recreate - should be different from the current one"
  exit(-1)
end

verbose = ARGV.delete("-v")
tag_to_recreate = ARGV.first
help if tag_to_recreate.nil?

current_branch = `git rev-parse --abbrev-ref HEAD`.chomp
raise "Should not run this when in master" if current_branch == 'master'

tags = `git fetch --tags; git tag -l`.split("\n")
tags_for_current_branch = tags.select{|l| l =~ /^#{current_branch}/}
raise "Cannot recreate a non-existent tag: #{tag_to_recreate.inspect}" unless tags_for_current_branch.include?(tag_to_recreate)

latest_tag = tags_for_current_branch.sort{|a,b| a.split('.').collect(&:to_i) <=> b.split('.').collect(&:to_i)}.last
raise "Cannot recreate anything other than the latest tag: latest: #{latest_tag.inspect}" if latest_tag != tag_to_recreate

diff_exists = `git diff #{current_branch}..#{latest_tag}`
puts diff_exists

if !diff_exists.empty?
  require File.expand_path('./kernel_override', File.dirname(__FILE__)) unless verbose.nil?

  system("git tag -d #{latest_tag}")
  system("git push -f origin :refs/tags/#{latest_tag}")
  system("git tag -f #{latest_tag}")
  system("git push --tags")
end
