#!/usr/bin/env ruby

require 'open3'
require File.expand_path('./kernel_override', File.dirname(__FILE__)) if ARGV.include?("-v")

branches = `git branch`.split("\n")
current_branch = branches.detect{|l| l =~ /^\*/}.gsub("\* ", "")
raise "Should not run this when in master" if current_branch == 'master'
tags = `git tag -l`.split("\n")
tags_for_current_branch = tags.select{|l| l =~ /^#{current_branch}/}
latest_tag = tags_for_current_branch.sort{|a,b| a.split('.').collect(&:to_i) <=> b.split('.').collect(&:to_i)}.last
diff_exists = `git diff #{current_branch}..#{latest_tag}`
if !diff_exists.empty?
  `git tag -d #{latest_tag}`
  `git push origin :refs/tags/#{latest_tag}`
  `git tag #{latest_tag}`
  `git push --tags`
end
