#!/bin/bash

if [ "$1" = "-h" ]; then
  echo "This script will find all git repositories within the specified 'FOLDER' (defaults to current dir)"
  echo "filtered by 'FILTER' (defaults to empty string) and for a minimum depth of 'MINDEPTH'"
  echo "(optional; defaults to 1) and a maximum depth of 'MAXDEPTH' (optional; defaults to 3);"
  echo "and then runs the specified commands in each of those git repos."
  echo "This script is not limited to only running 'git' commands!"
  echo ""
  echo "For eg:"
  echo "   FOLDER=dev MINDEPTH=2 run_all git status"
  echo "   FOLDER=dev MINDEPTH=2 run_all git branch -vv"
  echo "   FOLDER=dev MINDEPTH=2 run_all ls -l"
  echo "   FILTER=oss run_all ls -l"
  exit -1
fi

pushd() {
  command pushd "$@" > /dev/null
}

popd() {
  command popd "$@" > /dev/null
}

MINDEPTH=${MINDEPTH:-1}
MAXDEPTH=${MAXDEPTH:-3}
FOLDER=${FOLDER:-.}

date

tput setaf 3 2>/dev/null  # bright green text
echo "Finding git repos starting in folder '$FOLDER' for a min depth of $MINDEPTH and max depth of $MAXDEPTH"
if [ "$FILTER" != "" ]; then
  echo "Filtering with: $FILTER"
fi
tput sgr0 2>/dev/null # go back to normal text

DIRECTORIES=`find $FOLDER -mindepth $MINDEPTH -maxdepth $MAXDEPTH -name ".git" -type d | GREP_OPTIONS= grep "$FILTER" | sed "s/\.\///" | sed "s/\/\.git//" | sort`

if [[ "$FOLDER" == "." ]] && [[ "$PWD" == "$HOME" ]] || [[ "$FOLDER" == "$HOME" ]]; then
  # Note: This line will also remove '.git' from the current folder if the current folder is itself a git repo
  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\ | |" | sed "s|$HOME\/\ | |" | sed "s/\.git//"`
  # Note: This line will remove my repo in '~/Library' folder
  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\/Library\ ||" | sed "s|Library\ ||"`
  # Note: This line will remove my repo in '~/.vscode' folder
  DIRECTORIES=`echo $DIRECTORIES | sed "s|$HOME\/\.vscode\ ||" | sed "s|.vscode\ ||"`
fi

TOTAL_COUNT=`echo $DIRECTORIES | wc -w`

COUNT=1
for dir in $DIRECTORIES; do
  if [ -d $dir -a ! -h $dir ]; then
    tput setaf 2 2>/dev/null  # bright green text
    echo ">>>>>>>>>>>>>>>>>>>>> [$COUNT of $TOTAL_COUNT] "$*" (in $dir) <<<<<<<<<<<<<<<<<<<<"
    tput sgr0 2>/dev/null # go back to normal text
    pushd $dir
    bash -c "$*"
    popd
    let COUNT=COUNT+1
  fi
done

date
